name: Update Contributors
on:
  schedule:
    - cron: '0 0 * * *'  # Se ejecuta diariamente a medianoche
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}  # Usa el token de acceso personal

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install all-contributors-cli
        run: npm install -g all-contributors-cli

      - name: Generate Contributors List
        run: npx all-contributors generate

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "docs: Update contributors list"
          git push origin main
